#!/bin/bash

VERSION=$1
QTSDKPATH=/Users/tgil/Qt/5.2.1/clang_64/bin
APP=CoActionOS-Link
TEMPDIR=$APP
SIGNATURE=CoActionOS,\ Inc

NAME=`uname`

if [ "$NAME" != "Darwin" ]; then
	echo "This is not a Mac"
	exit 1
fi

if [ "$VERSION" = "" ]; then
	echo "Usage:  ../deploy <version>"
	exit 1
fi

make
if [ "$?" -ne "0" ]; then
	echo "Failed to Build"
	exit 1
fi

#use macdeployqt to deploy the application
$QTSDKPATH/macdeployqt ./$APP.app
if [ "$?" -ne "0" ]; then
	echo "Failed to run macdeployqt"
	exit 1
fi

echo "Create $TEMPDIR"
#Create a temporary directory if one doesn't exist
mkdir -p $TEMPDIR
if [ "$?" -ne "0" ]; then
	echo "Failed to create CoActionOS-Link folder"
	exit 1
fi

echo "Clean $TEMPDIR"
#Delete the contents of any previous builds
rm -Rf ./$TEMPDIR/*
if [ "$?" -ne "0" ]; then
	echo "Failed to clean CoActionOS-Link folder"
	exit 1
fi

echo "Move application bundle"
#Move the application to the temporary directory
mv ./$APP.app ./$TEMPDIR
if [ "$?" -ne "0" ]; then
	echo "Failed to move CoActionOS-Link.app"
	exit 1
fi

echo "Create symbolic link"
#Create a symbolic link to the applications folder
ln -s /Applications ./$TEMPDIR/Applications
if [ "$?" -ne "0" ]; then
	echo "Failed to create link to /Applications"
	exit 1
fi

echo "Create new disk image"
#Create the disk image
rm -f ./$APP-$VERSION.dmg
hdiutil create -srcfolder ./$TEMPDIR -format UDBZ ./$APP-$VERSION.dmg
if [ "$?" -ne "0" ]; then
	echo "Failed to create disk image"
	exit 1
fi

#delete the temporary directory
rm -Rf ./$TEMPDIR/*
if [ "$?" -ne "0" ]; then
	echo "Failed to clean CoActionOS-Link folder"
	exit 1
fi

exit 0
